// GenForm-NPM/React/genform-react/src/GenFormComponent.js
import React, { useEffect, useRef } from 'react';
import GenForm from '@genform/core';

function GenFormComponent({ elems, params }) {
  const formRef = useRef(null);

  useEffect(() => {
    const generatedForm = GenForm.toForm(document, {
      elems: elems,
      params: params
    });

    if (formRef.current) {
      formRef.current.appendChild(generatedForm);
    }
  }, [elems, params]);

  return (
    <div className="DynamicFormComponent">
      <header className="App-header">
        <div ref={formRef}></div>
      </header>
    </div>
  );
}

export default GenFormComponent;

// GenForm-NPM/Vue/lib/components/GenFormComponent.vue
<template>
  <div ref="formRef"></div>
</template>

<script setup>
import { onMounted, ref, defineProps } from 'vue'
import GenForm from '@genform/core'

const props = defineProps({
  elems: Array,
  params: Object
})

const formRef = ref(null)

onMounted(() => {
  const generatedForm = GenForm.toForm(document, {
    elems: props.elems,
    params: props.params
  })

  if (formRef.value instanceof HTMLElement) {
    formRef.value.innerHTML = ''
    formRef.value.appendChild(generatedForm)
  }
})
</script>
