// GenForm-NPM/Vue/genform-vue/src/App.vue
<template>
  <div id="app">
    <GenFormComponent :elems="customElems" :params="customParams" />
  </div>
</template>

<script lang="ts">
import { ref } from 'vue';
import GenFormComponent from './components/GenFormComponent.vue';

export default {
  components: {
    GenFormComponent,
  },
  setup() {
    const customElems = ref([
      {
        type: 'text',
        name: 'name',
        placeholder: 'Name'
      },
      {
        type: 'email',
        name: 'email',
        placeholder: 'Email'
      },
      {
        type: 'password',
        name: 'password',
        placeholder: 'Password'
      },
      {
        type: 'submit',
        value: 'Submit'
      },
      {
        type: 'reset',
        value: 'Reset'
      }
    ]);

    const customParams = ref({
      action: '/register',
      method: 'POST',
    });

    return { customElems, customParams };
  }
};

</script>

// GenForm-Tests/React/genform-react-tests/src/App.js
import './App.css';
import GenForm from '@genform/react';

function App() {
    const customElems = [
        {
          type: 'text',
          name: 'name',
          placeholder: 'Name',
        },
        {
          type: 'email',
          name: 'email',
          placeholder: 'Email',
        },
        {
          type: 'password',
          name: 'password',
          placeholder: 'Password',
        },
        {
          type: 'submit',
          value: 'Submit',
        },
      ]

  const customParams = {
        action: '/register',
        method: 'POST',
      }
  return (
    <div className="App">
      <header className="App-header">
        <GenForm elems={customElems} params={customParams}/>
      </header>
    </div>
  );
}

export default App;
