// GenForm-NPM/React/genform-react/src/GenFormComponent.js
import React, { useEffect, useRef } from 'react';
import GenForm from '@genform/core';

function GenFormComponent({ elems, params }) {
  const formRef = useRef(null);

  useEffect(() => {
    const generatedForm = GenForm.toForm(document, {
      elems: elems,
      params: params
    });

    if (formRef.current) {
      formRef.current.appendChild(generatedForm);
    }
  }, [elems, params]);

  return (
    <div className="DynamicFormComponent">
      <header className="App-header">
        <div ref={formRef}></div>
      </header>
    </div>
  );
}

export default GenFormComponent;

// GenForm-NPM/Vue/genform-vue/src/components/GenFormComponent.vue
<template>
  <div ref= "formRef"/>
</template>

<script lang="ts">
import { onMounted, ref } from "vue"
import GenForm from '@genform/core'

export default {
  name: 'GenFormComponent',
  props: {
    elems: Array,
    params: Object,
  },
  setup(props) {
    const formRef = ref(null);

    onMounted(() => {
      const generatedForm = GenForm.toForm(document, { 
        elems: props.elems, 
        params: props.params,
      });

      if (formRef.value) {
        formRef.value.innerHTML = '';
        formRef.value.appendChild(generatedForm);
      }
    });

    return {
      formRef,
    };
  },
};
</script>
